name: Moizz Auto Poster
on:
  schedule:
    - cron: '0 13 * * *' # This means 1:00 PM UTC every day
  workflow_dispatch: # This lets you press a button to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Tools
        run: |
          sudo apt install imagemagick
          pip install -U google-genai moviepy requests

      - name: Run AI Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python auto_moizz.py
